// GENERATED by scripts/sync-content.ts — do not edit.
//
// Static imports so `bun build --compile` bundles the content pack into the
// binary. This is what makes the CLI work on a first run with no network, which
// matters in a classroom.
import book_ai_first_java_programming from "../../books/ai-first-java-programming.json";
import book_ai_first_python_programming from "../../books/ai-first-python-programming.json";
import type { RawEntry } from "./types";

/** Version of the content pack baked into this binary. */
export const EMBEDDED_PACK_VERSION = "1.7.1";

export const EMBEDDED_BOOKS: RawEntry[] = [
  { filename: "ai-first-java-programming.json", book: book_ai_first_java_programming as never },
  { filename: "ai-first-python-programming.json", book: book_ai_first_python_programming as never },
];
