#!/usr/bin/env bun
/**
 * Copies book content out of @aifirst/content into ./books and regenerates the
 * embedded-content module.
 *
 * The books are committed into this repo so the CLI builds and tests without the
 * content package checked out beside it, and so a release is reproducible from a
 * single commit. `--check` verifies the committed copy is in sync, which is what
 * CI runs.
 *
 * Usage:  bun scripts/sync-content.ts [--check]
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const ROOT = join(import.meta.dir, "..");
const DEST_BOOKS = join(ROOT, "books");
const GENERATED = join(ROOT, "src", "content", "embedded.generated.ts");

const checkOnly = process.argv.includes("--check");

function findContentPackage(): string {
  const candidates = [
    join(ROOT, "..", "aifirstcontent"),
    join(ROOT, "node_modules", "@aifirst", "content"),
  ];
  for (const dir of candidates) {
    if (existsSync(join(dir, "books"))) return dir;
  }
  throw new Error(
    `Cannot find @aifirst/content. Run "bun install", or check out aifirstcontent beside this repo.`,
  );
}

const pkgDir = findContentPackage();
const srcBooks = join(pkgDir, "books");

const packVersion = (() => {
  const pkg = JSON.parse(readFileSync(join(pkgDir, "package.json"), "utf8"));
  return pkg.version as string;
})();

const filenames = readdirSync(srcBooks)
  .filter((f) => f.toLowerCase().endsWith(".json"))
  .sort();

if (filenames.length === 0) throw new Error(`No books found in ${srcBooks}`);

/** Turn a filename into a valid, stable identifier for the generated imports. */
const identFor = (filename: string) =>
  "book_" + filename.replace(/\.json$/i, "").replace(/[^a-zA-Z0-9]+/g, "_");

const generated = `// GENERATED by scripts/sync-content.ts — do not edit.
//
// Static imports so \`bun build --compile\` bundles the content pack into the
// binary. This is what makes the CLI work on a first run with no network, which
// matters in a classroom.
${filenames.map((f) => `import ${identFor(f)} from "../../books/${f}";`).join("\n")}
import type { RawEntry } from "./types";

/** Version of the content pack baked into this binary. */
export const EMBEDDED_PACK_VERSION = ${JSON.stringify(packVersion)};

export const EMBEDDED_BOOKS: RawEntry[] = [
${filenames.map((f) => `  { filename: ${JSON.stringify(f)}, book: ${identFor(f)} as never },`).join("\n")}
];
`;

// --- Compare or write ------------------------------------------------------

const currentGenerated = existsSync(GENERATED) ? readFileSync(GENERATED, "utf8") : "";
const bookDiffs: string[] = [];

for (const f of filenames) {
  const want = readFileSync(join(srcBooks, f), "utf8");
  const destPath = join(DEST_BOOKS, f);
  const have = existsSync(destPath) ? readFileSync(destPath, "utf8") : "";
  if (want !== have) bookDiffs.push(f);
}

const stale = existsSync(DEST_BOOKS)
  ? readdirSync(DEST_BOOKS).filter((f) => f.endsWith(".json") && !filenames.includes(f))
  : [];

if (checkOnly) {
  const problems = [
    ...bookDiffs.map((f) => `books/${f} differs from @aifirst/content`),
    ...stale.map((f) => `books/${f} is no longer in @aifirst/content`),
    ...(currentGenerated !== generated ? ["src/content/embedded.generated.ts is out of date"] : []),
  ];
  if (problems.length > 0) {
    console.error("✗ content is out of sync:\n");
    for (const p of problems) console.error(`  ${p}`);
    console.error(`\nRun "bun run sync-content" and commit the result.`);
    process.exit(1);
  }
  console.log(`✓ content in sync (pack ${packVersion}, ${filenames.length} book(s)).`);
} else {
  mkdirSync(DEST_BOOKS, { recursive: true });
  for (const f of filenames) {
    writeFileSync(join(DEST_BOOKS, f), readFileSync(join(srcBooks, f), "utf8"));
  }
  for (const f of stale) rmSync(join(DEST_BOOKS, f));
  mkdirSync(join(ROOT, "src", "content"), { recursive: true });
  writeFileSync(GENERATED, generated);
  console.log(
    `✓ synced pack ${packVersion}: ${filenames.length} book(s)` +
      (stale.length ? `, removed ${stale.length} stale` : ""),
  );
}
